spring.application.name=jwt

server.port=8082
#spring.datasource.url=jdbc:postgresql://localhost:5432/springsecurity
#spring.datasource.username=postgres
#spring.datasource.password=postgres
spring.datasource.url=jdbc:postgresql://pg-11f447e7-aratrin-375b.e.aivencloud.com:15912/defaultdb?sslmode=require
spring.datasource.username=${USER_NAME}
spring.datasource.password=${PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.user.password=user
jwt.secretkey=a-string-secret-at-least-256-bits-long